// vuejs/src/pages/Login.vue
<template>
  <section class="hero is-primary is-fullheight">
      <div class="hero-body">
        <div class="container">
          <div class="columns is-centered">
            <div class="column is-5-tablet is-4-desktop is-3-widescreen">
              <form class="box">
                <div class="field has-text-centered">
                  <img src="../assets/logo.png">
                </div>
                <div class="field">
                  <label class="label">Email</label>
                  <div class="control has-icons-left">
                    <input class="input" type="email" placeholder="e.g. alexjohnson@gmail.com" required
                          :class="{'is-danger': error.email}" v-model="form.email">
                    <span class="icon is-small is-left">
                      <i class="fa fa-envelope"></i>
                    </span>
                  </div>
                  <p class="help is-danger" v-if="error.email">Oops! Can't find user.</p>
                </div>
                <div class="field">
                  <label class="label">Password</label>
                  <div class="control has-icons-left">
                    <input class="input" type="password" placeholder="********" required
                          :class="{'is-danger': error.password}" v-model="form.password">
                    <span class="icon is-small is-left">
                      <i class="fa fa-lock"></i>
                    </span>
                  </div>
                  <p class="help is-danger" v-if="error.password">Password doesn't match our records.</p>
                </div>
                <div class="field">
                  <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                  </label>
                </div>
                <div class="field">
                  <button class="button is-success" @click.prevent="tryLogin">
                    Login
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
</template>

<script>
export default {
  name: "Login",
  data() {
    return {
      form: {
        email: "",
        password: ""
      },
      error: {
        email: false,
        password: false
      }
    }
  },
  methods: {
    tryLogin(){
      this.resetErrors();

      if(this.form.email !== 'user@bulma.com'){ return this.error.email = true;}
      if(this.form.password !== 'password'){ return this.error.password = true;}

      this.resetErrors();

      this.$router.push('dashboard');
    },
    resetErrors(){
      this.error.email = false;
      this.error.password = false;
    }
  }
}
</script>

<style>

</style>

// react-example/src/components/Login/Login.jsx
import React, { Component } from 'react';
import Logo from './../../assets/logo-bis.png';

class Login extends Component {
  render() {
    return (
      <section className="hero is-primary is-fullheight">
        <div className="hero-body">
          <div className="container">
            <div className="columns is-centered">
              <div className="column is-5-tablet is-4-desktop is-3-widescreen">
                <form className="box">
                  <div className="field has-text-centered">
                    <img src={Logo} width="167"/>
                  </div>
                  <div className="field">
                    <label className="label">Email</label>
                    <div className="control has-icons-left">
                      <input className="input" type="email" placeholder="e.g. alexjohnson@gmail.com" required/>
                      <span className="icon is-small is-left">
                        <i className="fa fa-envelope"></i>
                      </span>
                    </div>
                  </div>
                  <div className="field">
                    <label className="label">Password</label>
                    <div className="control has-icons-left">
                      <input className="input" type="password" placeholder="********" required/>
                      <span className="icon is-small is-left">
                        <i className="fa fa-lock"></i>
                      </span>
                    </div>
                  </div>
                  <div className="field">
                    <label className="checkbox">
                      <input type="checkbox" required/>
                      Remember me
                    </label>
                  </div>
                  <div className="field">
                    <button className="button is-success">
                      Login
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

export default Login;
